services:
  solana-solproxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-solproxy}_solana-solproxy
    restart: unless-stopped
    hostname: solana-solproxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./config.json:/app/conf.json
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "${PROXY_WSS_PORT:-7777}:7777"
      - "${PROXY_HTTP_PORT:-7778}:7778"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # Limit each log file to 10 megabytes
        max-file: "3"      # Keep up to 3 log files
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:7778?action=server-status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
